### ISSUE TITLE
Contribution

### ISSUE THREAD

**Issue by luizhrbueno** [christiankral/PhotoVoltaics#8]
How could I contribute to this library?
I developed a block to work with Modelica Electrical MultiPhase library as you can see in the figure below.
It has also reactive power control.

![image](https://cloud.githubusercontent.com/assets/25841359/23063395/a0ac9bde-f50a-11e6-9445-ba1fd9421a7b.png)

**Comment by christiankral** [comment]
You are very welcome to contribute. Please fork the library and make a pull request or just send me your model.

**Comment by luizhrbueno** [comment]
The idea of this improvement is to interface the PV system to the Power System library 

![image](https://cloud.githubusercontent.com/assets/25841359/23121294/20d7e776-f760-11e6-99c9-65b45a08217b.png)

**Comment by christiankral** [comment]
Manually incorporated your pull request in 92df23f. The following changes have additionally been performed:

In model ``MultiPhaseConverter``
- ``Blocks.Rotation_dq`` is replaced by ``Modelica.Electrical.Machines.SpacePhasors.Blocks.Rotator``
- ``Blocks.Park`` is replaced by ``Modelica.Electrical.Machines.SpacePhasors.Blocks.ToSpacePhasor toSpacePhasor`` and ``Modelica.Electrical.Machines.SpacePhasors.Blocks.Rotator`` 
- ``fromSpacePhasor`` is not diectly connected to the signal current source; instead a smoothing first order delay is used; this enables two things:
  * The resistors parallel to the voltages sources in PhotoVoltaics.Examples.SimpleModuleMultiPhase is not required any more
  * An ideal inductor between converter and voltage source does not cause the simulation model to fail

The following models are removed due to redundancy reasons
- ``Components.Blocks.MIMO ``
- ``Components.Blocks.Park``
- ``Components.Blocks.Rotation_dq``
- ``Components.Blocks.Icons``

**Comment by christiankral** [comment]
See #11

**Comment by christiankral** [comment]
Model ist re-structured and updated according to #12
